2013-05-08 21:47:36.883 [WARN ] [main] XmlBeanDefinitionReader - Ignored XML validation warning
org.xml.sax.SAXParseException: schema_reference.4: Failed to read schema document 'http://www.digitnexus.com/schema/mongodb/digit-mongodb.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.warning(ErrorHandlerWrapper.java:96)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:318)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:2541)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaWarning(XSDHandler.java:2532)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:1836)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:531)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:552)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2437)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1782)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:725)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:377)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2755)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:648)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:140)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:511)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:808)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:737)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:119)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:235)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:284)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:75)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:388)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:243)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadBeanDefinitions(AbstractGenericContextLoader.java:205)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:100)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
2013-05-08 21:47:36.913 [ERROR] [main] TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@1f8acdc] to prepare test instance [com.digitnexus.core.id.IdGenerateUtilTest@10b9279]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:157)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 24 in XML document from file [E:\work\digitnexus\code\DNPlatform\core\target\classes\spring\applicationContext-mongodb.xml] is invalid; nested exception is org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'digit:mongo-mapping-context'.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:396)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:243)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadBeanDefinitions(AbstractGenericContextLoader.java:205)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:100)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	... 28 more
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'digit:mongo-mapping-context'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:131)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:384)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:318)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:417)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3182)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1927)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:725)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:377)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2755)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:648)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:140)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:511)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:808)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:737)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:119)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:235)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:284)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:75)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:388)
	... 40 more
2013-05-08 21:51:03.936 [WARN ] [main] XmlBeanDefinitionReader - Ignored XML validation warning
org.xml.sax.SAXParseException: schema_reference.4: Failed to read schema document 'http://www.digitnexus.com/schema/mongodb/digit-mongodb.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.warning(ErrorHandlerWrapper.java:96)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:318)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:2541)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaWarning(XSDHandler.java:2532)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:1836)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:531)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:552)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2437)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1782)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:725)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:377)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2755)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:648)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:140)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:511)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:808)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:737)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:119)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:235)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:284)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:75)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:388)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:243)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadBeanDefinitions(AbstractGenericContextLoader.java:205)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:100)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
2013-05-08 21:51:03.946 [ERROR] [main] TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@16504fa] to prepare test instance [com.digitnexus.core.id.IdGenerateUtilTest@1a918d5]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:157)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 24 in XML document from file [E:\work\digitnexus\code\DNPlatform\core\target\classes\spring\applicationContext-mongodb.xml] is invalid; nested exception is org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'digit:mongo-mapping-context'.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:396)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:243)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadBeanDefinitions(AbstractGenericContextLoader.java:205)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:100)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	... 28 more
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'digit:mongo-mapping-context'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:131)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:384)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:318)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:417)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3182)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1927)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:725)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:377)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2755)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:648)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:140)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:511)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:808)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:737)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:119)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:235)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:284)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:75)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:388)
	... 40 more
2013-05-08 21:53:19.749 [ERROR] [main] TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@4c71d2] to prepare test instance [com.digitnexus.core.id.IdGenerateUtilTest@1a918d5]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:157)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 22 in XML document from file [E:\work\digitnexus\code\DNPlatform\core\target\classes\spring\applicationContext-mongodb.xml] is invalid; nested exception is org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'digit:mongo-mapping-context'.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:396)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:243)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadBeanDefinitions(AbstractGenericContextLoader.java:205)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:100)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	... 28 more
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'digit:mongo-mapping-context'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:131)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:384)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:318)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:417)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3182)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1927)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:725)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:377)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2755)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:648)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:140)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:511)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:808)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:737)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:119)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:235)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:284)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:75)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:388)
	... 40 more
2013-05-08 21:56:54.223 [WARN ] [main] RootClass - HHH000038: Composite-id class does not override equals(): com.digitnexus.core.id.UnitTestDomain
2013-05-08 21:56:54.223 [WARN ] [main] RootClass - HHH000039: Composite-id class does not override hashCode(): com.digitnexus.core.id.UnitTestDomain
2013-05-08 21:56:56.523 [WARN ] [main] ConfigurationFactory - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/D:/repository/net/sf/ehcache/ehcache-core/2.6.2/ehcache-core-2.6.2.jar!/ehcache-failsafe.xml
2013-05-08 21:56:58.533 [ERROR] [main] TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@19f1a8a] to prepare test instance [com.digitnexus.core.id.IdGenerateUtilTest@1a918d5]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:157)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in file [E:\work\digitnexus\code\DNPlatform\core\target\test-classes\spring\test\applicationContext-hibernate.xml]: Invocation of init method failed; nested exception is org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:587)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	... 28 more
Caused by: org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.hibernate.persister.internal.PersisterFactoryImpl.create(PersisterFactoryImpl.java:180)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:131)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:345)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1737)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1775)
	at org.springframework.orm.hibernate4.LocalSessionFactoryBuilder.buildSessionFactory(LocalSessionFactoryBuilder.java:251)
	at com.digitnexus.core.spring.hibernate4.LocalSessionFactoryBean.afterPropertiesSet(LocalSessionFactoryBean.java:325)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
	... 42 more
Caused by: org.hibernate.InstantiationException: could not instantiate test objectcom.digitnexus.core.domain.Email
	at org.hibernate.engine.internal.UnsavedValueFactory.instantiate(UnsavedValueFactory.java:49)
	at org.hibernate.engine.internal.UnsavedValueFactory.getUnsavedIdentifierValue(UnsavedValueFactory.java:68)
	at org.hibernate.tuple.PropertyFactory.buildIdentifierProperty(PropertyFactory.java:75)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:143)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:498)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:142)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.hibernate.persister.internal.PersisterFactoryImpl.create(PersisterFactoryImpl.java:158)
	... 50 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.hibernate.engine.internal.UnsavedValueFactory.instantiate(UnsavedValueFactory.java:46)
	... 60 more
Caused by: java.lang.NullPointerException
	at com.digitnexus.core.domain.DataObject.<init>(DataObject.java:26)
	at com.digitnexus.core.domain.Email.<init>(Email.java:29)
	... 65 more
2013-05-09 21:16:37.603 [WARN ] [main] RootClass - HHH000038: Composite-id class does not override equals(): com.digitnexus.core.id.UnitTestDomain
2013-05-09 21:16:37.623 [WARN ] [main] RootClass - HHH000039: Composite-id class does not override hashCode(): com.digitnexus.core.id.UnitTestDomain
2013-05-09 21:16:40.887 [WARN ] [main] ConfigurationFactory - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/D:/repository/net/sf/ehcache/ehcache-core/2.6.2/ehcache-core-2.6.2.jar!/ehcache-failsafe.xml
2013-05-09 21:16:42.765 [ERROR] [main] TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@3b9a5f] to prepare test instance [com.digitnexus.core.id.IdGenerateUtilTest@9d6065]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:157)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in file [E:\work\digitnexus\code\DNPlatform\core\target\test-classes\spring\test\applicationContext-hibernate.xml]: Invocation of init method failed; nested exception is org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:587)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	... 28 more
Caused by: org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.hibernate.persister.internal.PersisterFactoryImpl.create(PersisterFactoryImpl.java:180)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:131)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:345)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1737)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1775)
	at org.springframework.orm.hibernate4.LocalSessionFactoryBuilder.buildSessionFactory(LocalSessionFactoryBuilder.java:251)
	at com.digitnexus.core.spring.hibernate4.LocalSessionFactoryBean.afterPropertiesSet(LocalSessionFactoryBean.java:325)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
	... 42 more
Caused by: org.hibernate.InstantiationException: could not instantiate test objectcom.digitnexus.core.domain.Email
	at org.hibernate.engine.internal.UnsavedValueFactory.instantiate(UnsavedValueFactory.java:49)
	at org.hibernate.engine.internal.UnsavedValueFactory.getUnsavedIdentifierValue(UnsavedValueFactory.java:68)
	at org.hibernate.tuple.PropertyFactory.buildIdentifierProperty(PropertyFactory.java:75)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:143)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:498)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:142)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.hibernate.persister.internal.PersisterFactoryImpl.create(PersisterFactoryImpl.java:158)
	... 50 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.hibernate.engine.internal.UnsavedValueFactory.instantiate(UnsavedValueFactory.java:46)
	... 60 more
Caused by: java.lang.NullPointerException
	at com.digitnexus.core.domain.DataObject.<init>(DataObject.java:26)
	at com.digitnexus.core.domain.Email.<init>(Email.java:27)
	... 65 more
2013-05-11 19:30:52.366 [WARN ] [main] RootClass - HHH000038: Composite-id class does not override equals(): com.digitnexus.core.id.UnitTestDomain
2013-05-11 19:30:52.444 [WARN ] [main] RootClass - HHH000039: Composite-id class does not override hashCode(): com.digitnexus.core.id.UnitTestDomain
2013-05-11 19:30:56.297 [WARN ] [main] ConfigurationFactory - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/D:/repository/net/sf/ehcache/ehcache-core/2.6.2/ehcache-core-2.6.2.jar!/ehcache-failsafe.xml
2013-05-11 19:30:58.247 [ERROR] [main] TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@127f4f9] to prepare test instance [com.digitnexus.core.id.IdGenerateUtilTest@14b5f4a]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:157)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in file [E:\work\digitnexus\code\DNPlatform\core\target\test-classes\spring\test\applicationContext-hibernate.xml]: Invocation of init method failed; nested exception is org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:587)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	... 28 more
Caused by: org.hibernate.MappingException: Could not get constructor for org.hibernate.persister.entity.SingleTableEntityPersister
	at org.hibernate.persister.internal.PersisterFactoryImpl.create(PersisterFactoryImpl.java:180)
	at org.hibernate.persister.internal.PersisterFactoryImpl.createEntityPersister(PersisterFactoryImpl.java:131)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:345)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1737)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1775)
	at org.springframework.orm.hibernate4.LocalSessionFactoryBuilder.buildSessionFactory(LocalSessionFactoryBuilder.java:251)
	at com.digitnexus.core.spring.hibernate4.LocalSessionFactoryBean.afterPropertiesSet(LocalSessionFactoryBean.java:325)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
	... 42 more
Caused by: org.hibernate.InstantiationException: could not instantiate test objectcom.digitnexus.core.domain.Email
	at org.hibernate.engine.internal.UnsavedValueFactory.instantiate(UnsavedValueFactory.java:49)
	at org.hibernate.engine.internal.UnsavedValueFactory.getUnsavedIdentifierValue(UnsavedValueFactory.java:68)
	at org.hibernate.tuple.PropertyFactory.buildIdentifierProperty(PropertyFactory.java:75)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:143)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:498)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:142)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.hibernate.persister.internal.PersisterFactoryImpl.create(PersisterFactoryImpl.java:158)
	... 50 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.hibernate.engine.internal.UnsavedValueFactory.instantiate(UnsavedValueFactory.java:46)
	... 60 more
Caused by: java.lang.NullPointerException
	at com.digitnexus.core.domain.DataObject.<init>(DataObject.java:26)
	at com.digitnexus.core.domain.Email.<init>(Email.java:27)
	... 65 more
2013-05-22 20:43:53.559 [WARN ] [main] RootClass - HHH000038: Composite-id class does not override equals(): com.digitnexus.core.id.UnitTestDomain
2013-05-22 20:43:53.637 [WARN ] [main] RootClass - HHH000039: Composite-id class does not override hashCode(): com.digitnexus.core.id.UnitTestDomain
2013-05-22 20:44:00.626 [WARN ] [main] ConfigurationFactory - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/D:/repository/net/sf/ehcache/ehcache-core/2.6.2/ehcache-core-2.6.2.jar!/ehcache-failsafe.xml
2013-05-22 20:44:03.824 [WARN ] [main] AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [com.digitnexus.core.domain.Role]; using defaults.
2013-05-22 20:44:04.308 [WARN ] [main] AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [com.digitnexus.core.id.domain.IdHeader]; using defaults.
2013-05-22 20:44:04.323 [WARN ] [main] EhcacheAccessStrategyFactoryImpl - HHH020007: read-only cache configured for mutable entity [com.digitnexus.core.id.domain.IdHeader]
2013-05-22 20:44:04.994 [WARN ] [main] AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [org.hibernate.cache.spi.UpdateTimestampsCache]; using defaults.
2013-05-22 20:44:05.010 [WARN ] [main] AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [org.hibernate.cache.internal.StandardQueryCache]; using defaults.
2013-05-22 20:44:23.707 [ERROR] [main] DefaultListableBeanFactory - Destroy method on bean with name 'user' threw an exception
java.lang.NullPointerException
	at com.digitnexus.core.domain.User.hashCode(User.java:415)
	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:922)
	at org.springframework.orm.jpa.support.PersistenceAnnotationBeanPostProcessor.postProcessBeforeDestruction(PersistenceAnnotationBeanPostProcessor.java:357)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:193)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:499)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:475)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:443)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1078)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
2013-05-22 20:44:23.832 [ERROR] [main] TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@7aacc1] to prepare test instance [com.digitnexus.core.id.business.PojoIdGenerateServiceTest@17b0998]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:157)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailDaoImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.digitnexus.core.email.scheduler.EmailMessageScheduler com.digitnexus.core.email.dao.EmailDaoImpl.emailMessageScheduler; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailMessageScheduler' defined in file [E:\work\digitnexus\code\DNPlatform\core\target\classes\com\digitnexus\core\email\scheduler\EmailMessageScheduler.class]: Invocation of init method failed; nested exception is org.springframework.scheduling.SchedulingException: Failed to pause job EmailMessageSend; nested exception is org.quartz.JobPersistenceException: Couldn't obtain triggers for job: null [See nested exception: java.io.EOFException]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:287)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:605)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	... 28 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.digitnexus.core.email.scheduler.EmailMessageScheduler com.digitnexus.core.email.dao.EmailDaoImpl.emailMessageScheduler; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailMessageScheduler' defined in file [E:\work\digitnexus\code\DNPlatform\core\target\classes\com\digitnexus\core\email\scheduler\EmailMessageScheduler.class]: Invocation of init method failed; nested exception is org.springframework.scheduling.SchedulingException: Failed to pause job EmailMessageSend; nested exception is org.quartz.JobPersistenceException: Couldn't obtain triggers for job: null [See nested exception: java.io.EOFException]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:513)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:92)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:284)
	... 43 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailMessageScheduler' defined in file [E:\work\digitnexus\code\DNPlatform\core\target\classes\com\digitnexus\core\email\scheduler\EmailMessageScheduler.class]: Invocation of init method failed; nested exception is org.springframework.scheduling.SchedulingException: Failed to pause job EmailMessageSend; nested exception is org.quartz.JobPersistenceException: Couldn't obtain triggers for job: null [See nested exception: java.io.EOFException]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:872)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:814)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:731)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:485)
	... 45 more
Caused by: org.springframework.scheduling.SchedulingException: Failed to pause job EmailMessageSend; nested exception is org.quartz.JobPersistenceException: Couldn't obtain triggers for job: null [See nested exception: java.io.EOFException]
	at com.digitnexus.core.scheduler.SchedulerServiceImpl.resumeJob(SchedulerServiceImpl.java:67)
	at com.digitnexus.core.scheduler.MessageSchedulerBean$1.doInTransactionWithoutResult(MessageSchedulerBean.java:41)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:33)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.digitnexus.core.scheduler.MessageSchedulerBean.afterPropertiesSet(MessageSchedulerBean.java:25)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
	... 55 more
Caused by: org.quartz.JobPersistenceException: Couldn't obtain triggers for job: null [See nested exception: java.io.EOFException]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getTriggersForJob(JobStoreSupport.java:2135)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$33.execute(JobStoreSupport.java:2377)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$45.execute(JobStoreSupport.java:3739)
	at org.quartz.impl.jdbcjobstore.JobStoreCMT.executeInLock(JobStoreCMT.java:245)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInLock(JobStoreSupport.java:3735)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.resumeJob(JobStoreSupport.java:2373)
	at org.quartz.core.QuartzScheduler.resumeJob(QuartzScheduler.java:1308)
	at org.quartz.impl.StdScheduler.resumeJob(StdScheduler.java:406)
	at com.digitnexus.core.scheduler.SchedulerServiceImpl.resumeJob(SchedulerServiceImpl.java:65)
	... 61 more
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2280)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2749)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:779)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:279)
	at org.quartz.impl.jdbcjobstore.oracle.OracleDelegate.getObjectFromBlob(OracleDelegate.java:169)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTrigger(StdJDBCDelegate.java:1764)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggersForJob(StdJDBCDelegate.java:1688)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getTriggersForJob(JobStoreSupport.java:2132)
	... 69 more
2013-05-22 20:44:23.926 [DEBUG] [TestNG] ServerInfoUtil - 8752@mimi
2013-05-22 20:53:55.201 [WARN ] [main] RootClass - HHH000038: Composite-id class does not override equals(): com.digitnexus.core.id.UnitTestDomain
2013-05-22 20:53:55.216 [WARN ] [main] RootClass - HHH000039: Composite-id class does not override hashCode(): com.digitnexus.core.id.UnitTestDomain
2013-05-22 20:53:56.293 [WARN ] [main] ConfigurationFactory - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/D:/repository/net/sf/ehcache/ehcache-core/2.6.2/ehcache-core-2.6.2.jar!/ehcache-failsafe.xml
2013-05-22 20:53:57.822 [WARN ] [main] AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [com.digitnexus.core.domain.Role]; using defaults.
2013-05-22 20:53:58.102 [WARN ] [main] AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [com.digitnexus.core.id.domain.IdHeader]; using defaults.
2013-05-22 20:53:58.102 [WARN ] [main] EhcacheAccessStrategyFactoryImpl - HHH020007: read-only cache configured for mutable entity [com.digitnexus.core.id.domain.IdHeader]
2013-05-22 20:53:58.602 [WARN ] [main] AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [org.hibernate.cache.spi.UpdateTimestampsCache]; using defaults.
2013-05-22 20:53:58.633 [WARN ] [main] AbstractEhcacheRegionFactory - HHH020003: Could not find a specific ehcache configuration for cache named [org.hibernate.cache.internal.StandardQueryCache]; using defaults.
2013-05-22 20:54:11.035 [WARN ] [main] DefaultConfigurationBuilder - Internal error
org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source properties/config-integration.properties
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:259)
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238)
	at org.apache.commons.configuration.DefaultConfigurationBuilder$FileConfigurationProvider.getConfiguration(DefaultConfigurationBuilder.java:1412)
	at org.apache.commons.configuration.DefaultConfigurationBuilder$ConfigurationBeanFactory.createBean(DefaultConfigurationBuilder.java:1300)
	at org.apache.commons.configuration.beanutils.BeanHelper.createBean(BeanHelper.java:336)
	at org.apache.commons.configuration.beanutils.BeanHelper.createBean(BeanHelper.java:358)
	at org.apache.commons.configuration.beanutils.BeanHelper.createBean(BeanHelper.java:372)
	at org.apache.commons.configuration.DefaultConfigurationBuilder.createConfigurationAt(DefaultConfigurationBuilder.java:834)
	at org.apache.commons.configuration.DefaultConfigurationBuilder.initCombinedConfiguration(DefaultConfigurationBuilder.java:698)
	at org.apache.commons.configuration.DefaultConfigurationBuilder.getConfiguration(DefaultConfigurationBuilder.java:601)
	at com.digitnexus.core.util.ConfigUtil.init(ConfigUtil.java:61)
	at com.digitnexus.core.util.ConfigUtil.getConfig(ConfigUtil.java:27)
	at com.digitnexus.core.id.dao.AbstractBaseIdGenerateDao.<init>(AbstractBaseIdGenerateDao.java:22)
	at com.digitnexus.core.id.dao.PojoIdGenerateDaoImpl.<init>(PojoIdGenerateDaoImpl.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:990)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:943)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:872)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:814)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:731)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:485)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:92)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:284)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:605)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
2013-05-22 20:54:11.035 [WARN ] [main] DefaultConfigurationBuilder - Internal error
org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source properties/default/config-integration.properties
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:259)
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238)
	at org.apache.commons.configuration.DefaultConfigurationBuilder$FileConfigurationProvider.getConfiguration(DefaultConfigurationBuilder.java:1412)
	at org.apache.commons.configuration.DefaultConfigurationBuilder$ConfigurationBeanFactory.createBean(DefaultConfigurationBuilder.java:1300)
	at org.apache.commons.configuration.beanutils.BeanHelper.createBean(BeanHelper.java:336)
	at org.apache.commons.configuration.beanutils.BeanHelper.createBean(BeanHelper.java:358)
	at org.apache.commons.configuration.beanutils.BeanHelper.createBean(BeanHelper.java:372)
	at org.apache.commons.configuration.DefaultConfigurationBuilder.createConfigurationAt(DefaultConfigurationBuilder.java:834)
	at org.apache.commons.configuration.DefaultConfigurationBuilder.initCombinedConfiguration(DefaultConfigurationBuilder.java:698)
	at org.apache.commons.configuration.DefaultConfigurationBuilder.getConfiguration(DefaultConfigurationBuilder.java:601)
	at com.digitnexus.core.util.ConfigUtil.init(ConfigUtil.java:61)
	at com.digitnexus.core.util.ConfigUtil.getConfig(ConfigUtil.java:27)
	at com.digitnexus.core.id.dao.AbstractBaseIdGenerateDao.<init>(AbstractBaseIdGenerateDao.java:22)
	at com.digitnexus.core.id.dao.PojoIdGenerateDaoImpl.<init>(PojoIdGenerateDaoImpl.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:990)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:943)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:872)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:814)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:731)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:485)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:92)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:284)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:605)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
2013-05-22 20:54:12.922 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table ASSETLOCATION_TEST (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, status_code varchar2(255 char), timestamp timestamp, typecode varchar2(255 char), asset_id number(19,0), primary key (id))
2013-05-22 20:54:12.922 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2' at line 1
2013-05-22 20:54:12.922 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table ASSET_TEST (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, attachmentDesc varchar2(255 char), guid varchar2(255 char) not null, name varchar2(255 char), primary key (id), unique (guid))
2013-05-22 20:54:12.922 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2' at line 1
2013-05-22 20:54:12.922 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table COMM_ID_HEADER (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, mac varchar2(32 char), server_no number(10,0), primary key (id))
2013-05-22 20:54:12.922 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by va' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: comment on table COMM_ID_HEADER is 'ID header info'
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'comment on table COMM_ID_HEADER is 'ID header info'' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table COMM_MENU (id number(10,0) not null, content varchar2(32 char), from_src varchar2(1 char), menu_group varchar2(50 char), icon_url varchar2(64 char), is_valid number(19,0), layout_template varchar2(32 char), name varchar2(32 char), parent_id number(10,0), remark varchar2(100 char), sub_menu_from_way varchar2(32 char), menu_type varchar2(32 char), type_code varchar2(16 char), primary key (id))
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(10,0) not null, content varchar2(32 char), from_src varchar2(1 char), men' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table COMM_POJO_ID (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, item varchar2(96 char), max_id number(19,0), next_id number(19,0), is_useup number(1,0), header_id varchar2(255 char) not null, primary key (id))
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by va' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: comment on table COMM_POJO_ID is 'POJO ID'
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'comment on table COMM_POJO_ID is 'POJO ID'' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table EMAIL (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, attachment blob, attachment_name varchar2(255 char), body clob not null, from_address varchar2(255 char), host varchar2(255 char), inline_html char(1 char), loop_counter number(10,0), sent char(1 char), subject varchar2(255 char) not null, to_address varchar2(255 char) not null, primary key (id))
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table LOCATION (id number(19,0) not null, typecode varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, addr_line1 varchar2(255 char), addr_line2 varchar2(128 char) not null, city varchar2(255 char), country varchar2(255 char), lat_coor varchar2(255 char), lon_coor varchar2(255 char), state varchar2(255 char), text varchar2(255 char), primary key (id, typecode))
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, typecode varchar2(255 char) not null, clientID varchar2(2' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table MDM_ReceiveRecord (id number(19,0) not null, changeType varchar2(255 char), code varchar2(255 char), entityName varchar2(255 char), revision number(10,0) not null, status varchar2(255 char), subscriber varchar2(255 char), primary key (id))
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, changeType varchar2(255 char), code varchar2(255 char), e' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table MDM_SYNCRECORD (id number(19,0) not null, entityIdString varchar2(255 char), entityIdType varchar2(255 char), entityName varchar2(255 char), revId number(10,0) not null, revisionType varchar2(255 char), status varchar2(255 char), type varchar2(255 char), updateBy varchar2(255 char), primary key (id))
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, entityIdString varchar2(255 char), entityIdType varchar2(' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table PASSWORD_RESET_INFO (uuid varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, userName varchar2(255 char), primary key (uuid))
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by va' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table ProductMaster_flexFields (ProductMaster_id varchar2(255 char) not null, flexFields varchar2(255 char), flexFields_KEY varchar2(255 char), primary key (ProductMaster_id, flexFields_KEY))
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, flexFields varchar2(255 char), flexFields_KEY varch' at line 1
2013-05-22 20:54:12.938 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table REVCHANGES (REV number(10,0) not null, ENTITYNAME varchar2(255 char))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(10,0) not null, ENTITYNAME varchar2(255 char))' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table REVISIONS (id number(10,0) not null, timestamp number(19,0) not null, username varchar2(255 char), version varchar2(255 char), primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(10,0) not null, timestamp number(19,0) not null, username varchar2(255 ch' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table TEST_NON_DATAOBJECT (id number(19,0) not null, primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, primary key (id))' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table TEST_NO_LISTENER (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table UNITTEST_ACL_CHILD_ENTITY (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, date_property timestamp, dbl_property double precision, long_property number(19,0), str_property varchar2(255 char), parent_id varchar2(255 char), primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by va' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table UNITTEST_ACL_ENTITY (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, date_property timestamp, dbl_property double precision, long_property number(19,0), str_property varchar2(255 char), primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by va' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table UT_DOMAIN (name varchar2(64 char) not null, id varchar2(128 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, primary key (name, id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(64 char) not null, id varchar2(128 char) not null, clientID varchar2(25' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table Users (user_name varchar2(64 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, account_non_expired char(1 char) not null, account_non_locked char(1 char) not null, addr_line1 varchar2(128 char), addr_line2 varchar2(128 char), bemployee_id number(19,0), bphone varchar2(255 char), city varchar2(64 char), country varchar2(64 char), credentials_non_expired char(1 char) not null, email varchar2(64 char) not null unique, employee_id number(19,0), enabled char(1 char) not null, full_name varchar2(64 char) not null, localeString varchar(20) default 'en' not null, mobile varchar2(16 char), password varchar2(255 char) not null, password_temporary char(1 char) not null, postalcode varchar2(32 char), state varchar2(64 char), user_grp number(19,0), org_id varchar2(255 char), primary key (user_name), unique (email))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(64 char) not null, clientID varchar2(255 char) not null, created_by var' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table acl_expr_association (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, resource_name varchar2(255 char) not null, expression_id number(19,0) not null, permission_id varchar2(255 char) not null, role_id number(19,0) not null, primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table acl_expression (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, description varchar2(1024 char) not null, expression varchar2(2048 char) not null, expression_name varchar2(255 char) not null, primary key (id), unique (expression_name))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table comm_role_menu_associations (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, child_role_id number(19,0), menu_id number(10,0), role_id number(19,0), primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table comm_roles_menus (roles_id number(19,0) not null, menus_id number(10,0) not null, primary key (roles_id, menus_id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, menus_id number(10,0) not null, primary key (roles_id, me' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table filter_expressions (id number(19,0) not null, lower_limit varchar2(255 char), name varchar2(255 char) not null, search_operator varchar2(255 char) not null, upper_limit varchar2(255 char), primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, lower_limit varchar2(255 char), name varchar2(255 char) n' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table organizations (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, code varchar2(255 char) not null unique, name varchar2(64 char) not null, points varchar2(255 char), parent_id varchar2(255 char), primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by va' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table permissions (name varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, description varchar2(255 char), display_name varchar2(255 char), protected_resource varchar2(255 char) not null, resource_type varchar2(255 char) not null, user_operation number(10,0) not null, primary key (name), unique (user_operation, protected_resource))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by va' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table role_permission_associations (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, child_role_id number(19,0), permission_id varchar2(255 char), role_id number(19,0), primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table roles (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, name varchar2(255 char) not null, org_id varchar2(255 char), parent_id number(19,0), primary key (id), unique (name))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table roles_permissions (roles_id number(19,0) not null, permissions_name varchar2(255 char) not null, primary key (roles_id, permissions_name))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, permissions_name varchar2(255 char) not null, primary key' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table search_criteria (id number(19,0) not null, default_criteria char(1 char), display_key varchar2(255 char) not null, entity_name varchar2(255 char) not null, name varchar2(255 char) not null, visible char(1 char), primary key (id), unique (entity_name, name))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, default_criteria char(1 char), display_key varchar2(255 c' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table sort_expressions (id number(19,0) not null, ascending char(1 char), name varchar2(255 char) not null, primary key (id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, ascending char(1 char), name varchar2(255 char) not null,' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table srchcriteria_fltrexpr (search_criteria_id number(19,0) not null, filterExpressions_id number(19,0) not null, unique (filterExpressions_id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, filterExpressions_id number(19,0) not null, unique (filte' at line 1
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table srchcriteria_sortexpr (search_criteria_id number(19,0) not null, sortExpressions_id number(19,0) not null, unique (sortExpressions_id))
2013-05-22 20:54:12.954 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, sortExpressions_id number(19,0) not null, unique (sortExp' at line 1
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table test_categories (category_name varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, code varchar2(255 char) not null unique, category_description varchar2(255 char) not null, primary key (category_name))
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by va' at line 1
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table test_gen_article (id number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, big_decimal number(19,2), big_integer number(19,2), boolean_primitive number(1,0), boolean_wrapper number(1,0), date_column timestamp, double_primitive double precision, double_wrapper double precision, float_primitive float, float_wrapper float, int_primitive number(10,0), int_wrapper number(10,0), long_primitive number(19,0), long_wrapper number(19,0), name varchar2(255 char) not null unique, primary key (id))
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'number(19,0) not null, clientID varchar2(255 char) not null, created_by varchar2' at line 1
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table test_product_masters (id varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, config_descriminator varchar2(255 char), name varchar2(255 char) not null, category_name varchar2(255 char) not null, uom varchar2(255 char) not null, primary key (id))
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by va' at line 1
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table test_products (id varchar2(20 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, name varchar2(255 char) not null, physicaltag varchar2(255 char), tag1 varchar2(255 char) not null, tag2 varchar2(255 char), tag3 varchar2(255 char), manufacturer_id varchar2(255 char) not null, product_master_id varchar2(255 char) not null, primary key (id))
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(20 char) not null, clientID varchar2(255 char) not null, created_by var' at line 1
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table test_uom (name varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by varchar2(20 char), created_date timestamp, lock_version number(19,0), updated_by varchar2(255 char), updated_date timestamp, i18n_name varchar2(255 char) not null, primary key (name))
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(255 char) not null, clientID varchar2(255 char) not null, created_by va' at line 1
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create table users_roles (users_user_name varchar2(64 char) not null, roles_id number(19,0) not null, primary key (users_user_name, roles_id))
2013-05-22 20:54:12.969 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'varchar2(64 char) not null, roles_id number(19,0) not null, primary key (users_u' at line 1
2013-05-22 20:54:13.016 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table ASSETLOCATION_TEST add constraint FKD7BD0E0CACC52FBA foreign key (asset_id) references ASSET_TEST
2013-05-22 20:54:13.016 [ERROR] [main] SchemaExport - Table 'testapp.assetlocation_test' doesn't exist
2013-05-22 20:54:13.796 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table COMM_POJO_ID add constraint FKA8470183FF829E0C foreign key (header_id) references COMM_ID_HEADER
2013-05-22 20:54:13.796 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:13.827 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table ProductMaster_flexFields add constraint FKE2AB3900B19BFC3A foreign key (ProductMaster_id) references test_product_masters
2013-05-22 20:54:13.827 [ERROR] [main] SchemaExport - Table 'testapp.productmaster_flexfields' doesn't exist
2013-05-22 20:54:14.295 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table REVCHANGES add constraint FK727428C02ECD108A foreign key (REV) references REVISIONS
2013-05-22 20:54:14.295 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:14.311 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table UNITTEST_ACL_CHILD_ENTITY add constraint FK45EE93444BB58F93 foreign key (parent_id) references UNITTEST_ACL_ENTITY
2013-05-22 20:54:14.311 [ERROR] [main] SchemaExport - Table 'testapp.unittest_acl_child_entity' doesn't exist
2013-05-22 20:54:14.748 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table Users add constraint FK4E39DE8FF191F53 foreign key (org_id) references organizations
2013-05-22 20:54:14.748 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:15.122 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table acl_expr_association add constraint FK24477C4C49DE09C4 foreign key (role_id) references roles
2013-05-22 20:54:15.122 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:15.434 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table acl_expr_association add constraint FK24477C4C42CCDFA4 foreign key (permission_id) references permissions
2013-05-22 20:54:15.434 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:15.699 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table acl_expr_association add constraint FK24477C4C2AD46923 foreign key (expression_id) references acl_expression
2013-05-22 20:54:15.699 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:16.042 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table comm_role_menu_associations add constraint FK502F75FC306F7524 foreign key (menu_id) references COMM_MENU
2013-05-22 20:54:16.042 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:16.370 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table comm_role_menu_associations add constraint FK502F75FC3EC8C9A1 foreign key (child_role_id) references roles
2013-05-22 20:54:16.370 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:16.573 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table comm_role_menu_associations add constraint FK502F75FC49DE09C4 foreign key (role_id) references roles
2013-05-22 20:54:16.573 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:16.994 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table comm_roles_menus add constraint FKF3CEA23FD3DB0F6F foreign key (menus_id) references COMM_MENU
2013-05-22 20:54:16.994 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:17.431 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table comm_roles_menus add constraint FKF3CEA23FE7F6821D foreign key (roles_id) references roles
2013-05-22 20:54:17.431 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:17.758 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table organizations add constraint FK8258B9A0B69F27CD foreign key (parent_id) references organizations
2013-05-22 20:54:17.758 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:18.242 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table role_permission_associations add constraint FK9CF783B93EC8C9A1 foreign key (child_role_id) references roles
2013-05-22 20:54:18.242 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:18.648 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table role_permission_associations add constraint FK9CF783B949DE09C4 foreign key (role_id) references roles
2013-05-22 20:54:18.648 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:18.866 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table role_permission_associations add constraint FK9CF783B942CCDFA4 foreign key (permission_id) references permissions
2013-05-22 20:54:18.866 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:19.303 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table roles add constraint FK67A8EBDFF191F53 foreign key (org_id) references organizations
2013-05-22 20:54:19.303 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:19.584 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table roles add constraint FK67A8EBD73332510 foreign key (parent_id) references roles
2013-05-22 20:54:19.584 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:19.849 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table roles_permissions add constraint FK250AE02E7F6821D foreign key (roles_id) references roles
2013-05-22 20:54:19.849 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:20.442 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table roles_permissions add constraint FK250AE024F8AB7F foreign key (permissions_name) references permissions
2013-05-22 20:54:20.442 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:20.956 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table srchcriteria_fltrexpr add constraint FKBA27D015411B4F1 foreign key (search_criteria_id) references search_criteria
2013-05-22 20:54:20.956 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:21.268 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table srchcriteria_fltrexpr add constraint FKBA27D015CCE57DFD foreign key (filterExpressions_id) references filter_expressions
2013-05-22 20:54:21.268 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:21.643 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table srchcriteria_sortexpr add constraint FK9BFC46EF411B4F1 foreign key (search_criteria_id) references search_criteria
2013-05-22 20:54:21.643 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:21.908 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table srchcriteria_sortexpr add constraint FK9BFC46EFDE7EE5BD foreign key (sortExpressions_id) references sort_expressions
2013-05-22 20:54:21.908 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:21.908 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table test_product_masters add constraint FK6CBD6D5445A13E2A foreign key (category_name) references test_categories
2013-05-22 20:54:21.908 [ERROR] [main] SchemaExport - Table 'testapp.test_product_masters' doesn't exist
2013-05-22 20:54:21.908 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table test_product_masters add constraint FK6CBD6D54B5E36E26 foreign key (uom) references test_uom
2013-05-22 20:54:21.908 [ERROR] [main] SchemaExport - Table 'testapp.test_product_masters' doesn't exist
2013-05-22 20:54:21.924 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table test_products add constraint FK7A09C271225654F9 foreign key (product_master_id) references test_product_masters
2013-05-22 20:54:21.924 [ERROR] [main] SchemaExport - Table 'testapp.test_products' doesn't exist
2013-05-22 20:54:21.924 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table test_products add constraint FK7A09C2715423E746 foreign key (manufacturer_id) references organizations
2013-05-22 20:54:21.924 [ERROR] [main] SchemaExport - Table 'testapp.test_products' doesn't exist
2013-05-22 20:54:22.470 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table users_roles add constraint FKF6CCD9C6E7F6821D foreign key (roles_id) references roles
2013-05-22 20:54:22.470 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: alter table users_roles add constraint FKF6CCD9C6A4BB6C9D foreign key (users_user_name) references Users
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - Cannot add foreign key constraint
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create sequence ASSETLOCATION_TEST_SEQ_DB
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'sequence ASSETLOCATION_TEST_SEQ_DB' at line 1
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create sequence ASSET_TEST_SEQ_DB
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'sequence ASSET_TEST_SEQ_DB' at line 1
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create sequence TEST_NON_DATAOBJECT_SEQ_DB
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'sequence TEST_NON_DATAOBJECT_SEQ_DB' at line 1
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create sequence TEST_NO_LISTENER_SEQ_DB
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'sequence TEST_NO_LISTENER_SEQ_DB' at line 1
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create sequence hibernate_sequence
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'sequence hibernate_sequence' at line 1
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - HHH000389: Unsuccessful: create sequence test_gen_article_seq_db
2013-05-22 20:54:22.735 [ERROR] [main] SchemaExport - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'sequence test_gen_article_seq_db' at line 1
2013-05-22 20:54:22.750 [ERROR] [main] SchemaUpdate - HHH000319: Could not get database metadata
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'testapp.all_sequences' doesn't exist
	at sun.reflect.GeneratedConstructorAccessor79.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2809)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2758)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1612)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.hibernate.tool.hbm2ddl.DatabaseMetadata.initSequences(DatabaseMetadata.java:149)
	at org.hibernate.tool.hbm2ddl.DatabaseMetadata.<init>(DatabaseMetadata.java:70)
	at org.hibernate.tool.hbm2ddl.DatabaseMetadata.<init>(DatabaseMetadata.java:63)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:196)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:178)
	at com.digitnexus.core.tool.SchemaExporterListener.onApplicationEvent(SchemaExporterListener.java:87)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
2013-05-22 20:54:22.750 [ERROR] [main] SchemaUpdate - HHH000299: Could not complete schema update
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'testapp.all_sequences' doesn't exist
	at sun.reflect.GeneratedConstructorAccessor79.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2809)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2758)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1612)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.hibernate.tool.hbm2ddl.DatabaseMetadata.initSequences(DatabaseMetadata.java:149)
	at org.hibernate.tool.hbm2ddl.DatabaseMetadata.<init>(DatabaseMetadata.java:70)
	at org.hibernate.tool.hbm2ddl.DatabaseMetadata.<init>(DatabaseMetadata.java:63)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:196)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:178)
	at com.digitnexus.core.tool.SchemaExporterListener.onApplicationEvent(SchemaExporterListener.java:87)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
	at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
	at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:321)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextPrepareTestInstance(AbstractTestNGSpringContextTests.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
2013-05-22 20:54:23.156 [DEBUG] [main] CustomMessageSource - Loading properties [messages.properties] with encoding 'UTF-8'
2013-05-22 20:54:23.172 [DEBUG] [main] CustomMessageSource - No properties file found for [classpath:org/springframework/security/messages_zh] - neither plain properties nor XML
2013-05-22 20:54:23.172 [DEBUG] [main] CustomMessageSource - Loading properties [messages_zh_CN.properties] with encoding 'UTF-8'
2013-05-22 20:54:23.172 [DEBUG] [main] CustomMessageSource - No properties file found for [classpath:properties/i18n/resourceBundleCore] - neither plain properties nor XML
2013-05-22 20:54:23.172 [DEBUG] [main] CustomMessageSource - No properties file found for [classpath:properties/i18n/resourceBundleCore_zh] - neither plain properties nor XML
2013-05-22 20:54:23.172 [DEBUG] [main] CustomMessageSource - Loading properties [resourceBundleCore_zh_CN.properties] with encoding 'UTF-8'
2013-05-22 20:54:23.172 [DEBUG] [main] CustomMessageSource - No properties file found for [classpath:properties/i18n/resourceBundleTest] - neither plain properties nor XML
2013-05-22 20:54:23.172 [DEBUG] [main] CustomMessageSource - No properties file found for [classpath:properties/i18n/resourceBundleTest_zh] - neither plain properties nor XML
2013-05-22 20:54:23.187 [DEBUG] [main] CustomMessageSource - Loading properties [resourceBundleTest_zh_CN.properties] with encoding 'UTF-8'
2013-05-22 20:54:25.481 [DEBUG] [TestNG] ServerInfoUtil - 5684@mimi
